- .github/workflows/node.js.yml
This commit, fixes the issue that the deploy on Dev only occurs after per-release which depends on working ref.
> Fix condition for CD pre-release

- src/dashboard.meta.tsx
This is to avoid re-refresh of the page when side nav is clicked.
> Use esm-framework for navigation

- src/forms/components/inputs/_input.scss
This fixes the issue with the missing validation error for some questions.
- Adds validation colour.
- Removes fontSize.(Incase in font size when validation error is shown)
Related Ticket: [ohri-275](https://ohri.atlassian.net/browse/OHRI-275)
> OHRI-275 Form validation errors

- src/covid/covid.scss
- src/covid/pages/lab-results.encounter-list.tsx
> Include initial layout, empty state, tabs

- src/components/encounter-list/encounter-list.component.tsx
- src/constants.ts
- OHRI-404: Short names and synonyms for ALL lists
- Added `names:(uuid,conceptNameType,name)` to retrieve `conceptNames` of coded value
- Encounter lists to first check for short name else default to the default `fully specified`
> OHRI-404: Short names and synonyms for ALL lists

- src/packages/covid/forms/lab-order-form/1.0.json
This also tackles the Cancel lab Order error in the Lab Test for Lab Orders created in as part of the Covid Assessment Form.
> OHRI-493: Edit Lab Result

- src/api/api.ts
OHRI-622 Make HIV status blank when patient is first added to pre-test list
> OHRI-622 Blank HIV status when patient is first added to pre-test list

- src/covid/pages/lab-results.encounter-list.tsx
- src/forms/ohri-form.component.tsx
- src/index.ts
- src/links/form-render-app-menu-link.component.tsx
This commit covers the following:
- Fixes covid lab result column in the lab results widget
- Adds form render test link to menu items
- Temporarily unmount toggle from form's header that is breaking the extension system
> OHRI-650: Show correct test results

- src/packages/hiv/forms/care-and-treatment/art-therapy/1.0.json
Removed validations on Notes field so that form can save even without notes.
> OHRI-781 ART Therapy form not saving

- packages/esm-commons-lib/src/components/data-table/o-table.component.tsx
- packages/esm-commons-lib/src/components/encounter-tile/encounter-tile.component.tsx
- packages/esm-commons-lib/src/components/lazy-cell/lazy-cell.component.tsx
Example usage:
```js
},
{
key: 'outcome',
header: t('outcome', 'Outcome'),
getValue: (encounter) => {
const valueY = await fetchLazyValue();
return getDisplayFromEncounterBasedOnValueY(encounter, valueY)
},
},
```
> Add support for lazy cell values in Encounter lists

- packages/esm-cervical-cancer-app/package.json
- packages/esm-hiv-app/package.json
- packages/esm-ohri-pmtct-app/package.json
- yarn.lock
The 'swr' entrie(s) under peer dependencies causes conflicts of the installed package by yarn with what is required by the forms engine.
> 'swr' npm-package should only be defined as a devDependency

- packages/esm-commons-lib/src/hooks/usePatientList.tsx
- packages/esm-hiv-app/src/views/hts/home/patient-tabs/ohri-patient-tabs.component.tsx
Ohri 1408: "post-test counselling" removed from HTS menu options
> OHRI-1408 "post-test counselling" removed from HTS menu options

- packages/esm-ohri-core-app/src/ohri-dashboard/side-menu/ohri-dashboard-side-nav.component.tsx
- packages/esm-ohri-core-app/translations/en.json
- "Programs" on ohri-dashboard-side-nav.component changed to "Programmes"
- Added "programmes" : "Programmes" to the ohri-core translation file.
> Ohri 1419: Changing programs to Programmes.

- packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/hiv-exposed-infant.component.tsx
Action buttons for Visit section NOW work on the MNCH summary
> OHRI-1547: Action buttons for Visit section must work on the MNCH summary

- packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/previous-pregnancies.component.tsx
Action buttons for Visit section to work on the previous pregnancies
> OHRI-1600: Action buttons for Visit section to work on the previous pregnancies

- packages/esm-ohri-core-app/src/ohri-dashboard/ohri-dashboard.component.tsx
- packages/esm-ohri-core-app/src/routes.json
This PR fixes:
- The Home Dashboard (OHRI-1593)
- Loading isolated dashboards (dbs that are associated with any folders) at index 0 under the programs section.
Attachments:
> Fix issue with loading links under the programs section

- packages/esm-commons-lib/src/dashboards/DashboardExtension.tsx
- packages/esm-commons-lib/src/dashboards/createDashboard.tsx
- packages/esm-commons-lib/src/dashboards/dashboardextension.scss
- packages/esm-commons-lib/src/types/index.ts
- packages/esm-ohri-pmtct-app/src/dashboard.meta.tsx
- packages/esm-ohri-pmtct-app/src/index.ts
- packages/esm-ohri-pmtct-app/src/routes.json
The issue with this was because of the discrepancy between how the patient chart functions were working vs how our custom functions were working. Issue was only happening with PMTCT because those are the only places with the custom functions;
- There's no need for the `createDashboardLinkWithCustomTitle` anymore so i deleted it
- Introduced `moduleName` to match patient chart spec
> OHRI-1440 fixes to active link on patient chart with custom functions

- packages/esm-ohri-pmtct-app/src/api/api.ts
- packages/esm-ohri-pmtct-app/src/views/summary-tabs/maternal-child-summary-tiles.component.tsx
> PMTCT MNCH Summary Reports

- packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/current-pregnancy.component.tsx
> OHRI-1739 Fix mother-baby linkage on the MNCH

- packages/esm-ohri-pmtct-app/src/index.ts
- packages/esm-ohri-pmtct-app/src/utils/ptracker-forms-helpers.ts
[OHRI-1819](https://ohri.atlassian.net/browse/OHRI-1819): Child(s) PTracker ID in L&D form Validated or autopulated based on the birth count form engine helper function
This PR add support to auto populate the PTRacker ID for the Child in full based on the birth count and the mother’s ID i.e. the system should assign PTracker ID to the babies for baby number 1 mothers' ID and 1 for child 1 and 2 for child 2 and add three for child 3 etc
https://github.com/UCSF-IGHS/openmrs-esm-ohri/assets/19629227/4064ddd1-ea76-4514-b11a-7bb10c124344
[OHRI-1819]: https://ohri.atlassian.net/browse/OHRI-1819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (feat) add helper function to auto generate infant ptracker id

- package.json
- packages/esm-tb-app/src/dashboard.meta.tsx
- packages/esm-tb-app/src/index.ts
- packages/esm-tb-app/src/routes.json
- packages/esm-tb-app/src/views/patient-summary/tb-patient-summary.component.tsx
- packages/esm-tb-app/src/views/program-management/maternal-health.component.tsx
- packages/esm-tb-app/src/views/program-management/tabs/mdr-tb.component.tsx
- packages/esm-tb-app/src/views/program-management/tabs/tb-patient-tracing.component.tsx
- packages/esm-tb-app/src/views/tb-contact-listing/tb-contact-list.component.tsx
- packages/esm-tb-app/src/views/treatment-and-follow-up/tb-treatment-follow-up.component.tsx
- packages/esm-tb-app/translations/en.json
> OHRI-1994 Add TB Program menu and tabs shell on the patient chart

- packages/esm-tb-app/src/views/patient-summary/tb-patient-summary.component.tsx
Previously the TB summary table for TB cases was having call to action. This wasn't meant to be the case because the summary is meant only for viewing and not adding data. 
Empty State
With Data
Follow up fix for https://ohri.atlassian.net/browse/OHRI-2013
> OHRI-2013 disable form launch action from TB previous cases

- packages/esm-commons-lib/src/components/cohort-patient-list/cohort-patient-list.component.tsx
- packages/esm-tb-app/src/views/dashboard/patient-list-tabs/tb-patient-list-tabs.component.tsx
This PR populates appointment date  on the TB dashboard summary. In general it also allows the cohort list to pull concepts from more than one encounter type.
https://github.com/UCSF-IGHS/openmrs-esm-ohri/assets/12844964/29fd4b52-b811-4923-a70a-027ad849b744
> OHRI-2095 Populate the missing appointment date on the TB dashboard summary

- packages/esm-tb-app/src/dashboard.meta.tsx
- packages/esm-tb-app/src/index.ts
- packages/esm-tb-app/src/routes.json
- packages/esm-tb-app/src/views/tpt/program-management/tabs/tpt-enrolment.component.tsx
- packages/esm-tb-app/src/views/tpt/program-management/tabs/tpt-treatment.component copy.tsx
- packages/esm-tb-app/src/views/tpt/program-management/tpt-program-management.tsx
- packages/esm-tb-app/translations/en.json
This PR adds the TPT folder on the clinical perspective as well as the program management and it's tabs
> OHRI-2122 Add Program Management under the TPT Program

- .github/workflows/node.master.js.yml
This removes the condition to publish release on push to master. Release will be limited to creating a new release on github. This will avoid unnecessary release deployments
> (chore) remove condition for release on master push

- packages/esm-tb-app/src/dashboard.meta.tsx
- packages/esm-tb-app/src/routes.json
- packages/esm-tb-app/translations/en.json
Add TB Prevention link under Tuberculosis program in the clinical perspectives
Update--> the TB Prevention link comes first followed by TB Treatment.
> OHRI-2109: Add TB Prevention link under Tuberculosis program in the clinical perspectives

- packages/esm-tb-app/src/views/tpt/patient-summary/patient-summary.component.tsx
PR fixes an issue where the previous Cases on the TPT patient summary wasn't loading
> OHRI-2121 (fix) Load Previous Cases on patient summary

- package.json
- packages/esm-opd-app/package.json
- packages/esm-opd-app/src/config-schema.ts
- packages/esm-opd-app/src/dashboard.meta.tsx
- packages/esm-opd-app/src/dashboard.scss
- packages/esm-opd-app/src/declarations.d.tsx
- packages/esm-opd-app/src/index.ts
- packages/esm-opd-app/src/root.scss
- packages/esm-opd-app/src/routes.json
- packages/esm-opd-app/src/setupTests.ts
- packages/esm-opd-app/translations/en.json
- packages/esm-opd-app/tsconfig.json
- packages/esm-opd-app/webpack.config.js
- yarn.lock
> opd package on the ohri clinical views

- packages/esm-commons-lib/package.json
- packages/esm-commons-lib/src/components/cohort-patient-list/helpers.tsx
- packages/esm-commons-lib/src/components/encounter-list/encounter-list.component.tsx
- packages/esm-commons-lib/src/components/encounter-list/helpers.ts
- packages/esm-commons-lib/src/index.ts
- packages/esm-commons-lib/src/routes.json
- packages/esm-commons-lib/src/workspace/ohri-workspace-utils.ts
- packages/esm-hiv-app/src/views/hts/lab-results/lab-results-form-viewer.tsx
- yarn.lock
- This PR updates the `openmrs` and `common-lib` versions, this necessitated some changes since some workspace functions were moved to other places or are no longer being exported. But this fixes the workspace bugs we have been seeing.
- This PR also updates the `openmrs` and common lib versions inside the `ohri-esm-commons-lib`.
Uploading Workspaces-fix.mov…
- No ticket
> (Upgrade): Update the esm-patient-common-lib version.

- packages/esm-commons-lib/src/api/api.ts
- packages/esm-commons-lib/src/types/index.ts
- packages/esm-ohri-pmtct-app/src/views/mch-summary/mch-summary.component.tsx
- packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/current-pregnancy.component.tsx
This pr address the following; 
Populate 3 mamba report for the MNCH Summary ;
1. [ ] no_of_anc_visits
2. [ ] mother_status
3. [ ] estimated_date_of_delivery
4. [ ] mother_hiv_status
> populate mamba reports

- packages/esm-commons-lib/src/utils/summary-card-config-builder.ts
- packages/esm-tb-app/src/config-schema.ts
- packages/esm-tb-app/src/views/patient-summary/recent-tb-config.json
- packages/esm-tb-app/src/views/patient-summary/tb-patient-summary.component.tsx
- packages/esm-tb-app/src/views/patient-summary/visits-config.json
- packages/esm-tb-app/src/views/program-management/tb-program-management-config.json
- packages/esm-tb-app/src/views/program-management/tb-program-management.tsx
- packages/esm-tb-app/src/views/tb-contact-listing/tb-contact-list.component.tsx
- packages/esm-tb-app/src/views/tb-contact-listing/tb-contact-listing-config.json
- packages/esm-tb-app/src/views/tpt/patient-summary/patient-summary.component.tsx
- packages/esm-tb-app/src/views/tpt/patient-summary/recent-tpt-config.json
- packages/esm-tb-app/src/views/tpt/patient-summary/tpt-previous-cases-config.json
- packages/esm-tb-app/src/views/tpt/patient-summary/tpt-visits-config.json
- packages/esm-tb-app/src/views/tpt/program-management/tpt-program-management-config.json
- packages/esm-tb-app/src/views/tpt/program-management/tpt-program-management.tsx
- packages/esm-tb-app/src/views/treatment-and-follow-up/tb-treatment-follow-up.component.tsx
- packages/esm-tb-app/src/views/treatment-and-follow-up/tb-treatment-followup-config.json
[screencast-from-2024-06-14-15-23-02_GXm3zwCD.webm](https://github.com/UCSF-IGHS/openmrs-esm-ohri/assets/130601439/73f0afe1-b173-41d2-848a-9c44ba0df279)
- https://ohri.atlassian.net/browse/OHRI-2233
> Use concept keys from the default schema in TB/TPT

- packages/esm-tb-app/src/views/patient-summary/previous-cases-config.json
- This PR does a small refactor for using config keys instead of hardcoded concept values in TB
- https://ohri.atlassian.net/browse/OHRI-2234
> (Fix) Refactor TB workflow schema to use config keys not hardcoded uuids.

- packages/esm-commons-lib/src/api/api.ts
- packages/esm-commons-lib/src/components/card-summary/helpers.ts
- packages/esm-commons-lib/src/components/card-summary/summary-card.component.tsx
- packages/esm-commons-lib/src/constants.ts
- packages/esm-commons-lib/src/utils/encounter-list-config-builder.ts
- packages/esm-commons-lib/src/utils/encounter-list-utils.ts
- packages/esm-commons-lib/src/utils/schema-manipulation.ts
- packages/esm-commons-lib/src/utils/summary-card-config-builder.ts
- packages/esm-ohri-pmtct-app/src/config-schema.ts
- packages/esm-ohri-pmtct-app/src/views/child-health/child-health-config.json
- packages/esm-ohri-pmtct-app/src/views/child-health/child-health.component.tsx
- packages/esm-ohri-pmtct-app/src/views/maternal-health/maternal-health-config.json
- packages/esm-ohri-pmtct-app/src/views/maternal-health/maternal-health.component.tsx
- packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/appointments-config.json
- packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/arv-therapy-config.json
- packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/current-pregnancy.component.tsx
- packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/hiv-exposed-family-summary-config.json
- packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/hiv-exposed-infant-summary-config.json
- packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/hiv-exposed-infant.component.tsx
- packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/infant-summary-config.json
- packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/mother-previous-visit.json
- packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/recent-pregnancy-config.json
-This pr refactors the code in the pmtct patient summary to use the new workflows approach
> (refactor) Add workflows to pmtct summary in patient chart

- jest.config.js
- packages/esm-commons-lib/src/components/cohort-patient-list/helpers.tsx
- packages/esm-commons-lib/src/components/encounter-list/encounter-list.component.tsx
- packages/esm-commons-lib/src/hooks/useEncounterRows.ts
- packages/esm-commons-lib/src/workspace/ohri-workspace-utils.ts
- packages/esm-hiv-app/src/views/hts/lab-results/lab-results-form-viewer.tsx
- yarn.lock
This PR fixes 2 bugs that were noted in the behaviour of the encounter list:
1. In case the form launcher's visibility was based on some condition, upon saving an encounter, the list would be refreshed but the launch condition wouldn't hence leading to undesirable behaviour.
2. The list would properly refresh whenever an encounter is deleted, however in cases where the list had only one entry, it wouldn't refresh after deletion.
https://github.com/UCSF-IGHS/openmrs-esm-ohri/assets/12844964/d5ca2c77-3efd-46cf-9427-1864aedcc4de
https://github.com/UCSF-IGHS/openmrs-esm-ohri/assets/12844964/6fe19756-3078-4e66-a9a7-8e78d3f48f53
> (fix) Improve encounter list behaviour

- packages/esm-commons-lib/src/components/cohort-patient-list/cohort-patient-list.component.tsx
- packages/esm-commons-lib/src/components/cohort-patient-list/helpers.tsx
- yarn.lock
- Change Workspace window to use the new WorkspaceContainer
- Fix some dependency warnings
- No ticket
> (Fix) Use the new workspace container

- .github/workflows/node.working.js.yml
- .yarnrc.yml
- package.json
- packages/esm-cervical-cancer-app/package.json
- packages/esm-commons-lib/package.json
- packages/esm-commons-lib/src/components/encounter-list/encounter-list.component.tsx
- packages/esm-commons-lib/src/components/encounter-list/helpers.ts
- packages/esm-commons-lib/src/hooks/useEncounterRows.ts
- packages/esm-covid-app/package.json
- packages/esm-form-render-app/package.json
- packages/esm-hiv-prevention-app/package.json
- packages/esm-ohri-core-app/package.json
- packages/esm-ohri-pmtct-app/package.json
- packages/esm-opd-app/package.json
- packages/esm-tb-app/package.json
- packages/esm-tb-app/src/index.ts
- packages/esm-tb-app/src/routes.json
- packages/esm-tb-app/src/views/tpt/program-management/tabs/tpt-treatment.component copy.tsx
- yarn.lock
Updating dev with changes that had been made directly to master branch (ET workspace and encounterlist refresh work)
> Merge master to dev 20240703

- packages/esm-ohri-pmtct-app/src/pmtct/patient-chart/child-health/child-health.component.tsx
- packages/esm-ohri-pmtct-app/src/pmtct/patient-chart/maternal-health/maternal-health.component.tsx
- packages/esm-ohri-pmtct-app/src/pmtct/patient-chart/mch-summary/tabs/current-pregnancy.component.tsx
Refactor tab and use the reusable tabs component (PMTCT)
> OHRI-2263 Refactor tab and use the reusable tabs component (PMTCT)

- package.json
- packages/esm-ohri-pmtct-app/src/config-schema.ts
- packages/esm-ohri-pmtct-app/src/pmtct/home-dashboard/maternal-child-summary-tiles.component.tsx
- packages/esm-ohri-pmtct-app/src/pmtct/patient-chart/mch-summary/mch-summary.component.tsx
- packages/esm-ohri-pmtct-app/src/pmtct/patient-chart/mch-summary/tabs/current-pregnancy.component.tsx
- packages/esm-ohri-pmtct-app/src/pmtct/patient-chart/mch-summary/tabs/hiv-exposed-infant.component.tsx
https://github.com/user-attachments/assets/db7e0535-eb47-446f-8602-fb8179bac12b
https://github.com/user-attachments/assets/d9ca11b0-a1e0-450e-a0ac-d029db941a48
> (Enhancement) Make MNCH Summary widgets, MCH tiles on home Dashboard configurable

- packages/esm-commons-lib/src/components/encounter-list/helpers.ts
Whenever a form is cancelled, the `clinical-forms-workspace `is automatically opened. This however shouldn't be the case if the form wasn't opened from the `clinical-forms-workspace` in the first place. This PR seeks to resolve the issue.
Before:
https://github.com/user-attachments/assets/ab3f279e-6da9-4eac-b5ad-9a8db1d9b431
After:
https://github.com/user-attachments/assets/af85cc2b-0565-42f0-abaa-35a3ed76525f
> (feat) disable Auto opening of Clinical-forms-workspace on form cancellation

- packages/esm-commons-lib/src/api/types.ts
- packages/esm-commons-lib/src/components/encounter-list/encounter-list.component.tsx
- packages/esm-commons-lib/src/components/encounter-list/encounter-list.test.tsx
- packages/esm-commons-lib/src/hooks/useEncounterRows.ts
- packages/esm-hiv-app/src/views/hiv-testing-services/tab-list/hts-overview-list.component.tsx
- yarn.lock
- I have fetch the total and passed the startIndex and limit to the endpoint
https://github.com/user-attachments/assets/4ac30c07-4741-4d21-be6a-f6a415585b16
No ticket
> (Fix) Fix the Encounters pagination by leveraging the backend
