UCSF-IGHS/openmrs-esm-ohri

src/index.ts

We agreed with @alaboso that this will be handled via the server import maps.

Removing patient dashboards config

---

src/components/patient-banner/patient-banner.scss
src/forms/_form.scss
src/forms/components/page/_page.scss
src/forms/components/sidebar/ohri-form-sidebar.component.tsx
src/forms/ohri-form.component.tsx
src/root.scss

This PR fixes the scrolling issue on select.

OHRI-92 : Handle scroll

---

package-lock.json
package.json
src/components/patient-banner/patient-banner.scss
src/forms/_form.scss
src/forms/components/page/ohri-form-page.tsx
src/forms/components/sidebar/ohri-form-sidebar.component.scss
src/forms/components/sidebar/ohri-form-sidebar.component.tsx
src/forms/ohri-form.component.tsx
src/root.scss

This PR addresses the following feature and bug fix.

Ohri 92 scroll

---

src/dashboard.meta.tsx
src/hts/encounters-list/hts-overview-list.component.tsx

Below SideNav made
Working on the Active Visit Side Pop-up, HIV Positive notification

OHRI-157-patient-header-include-side-nav-search-hiv-test 

---

package-lock.json
package.json
src/api/api.ts
src/components/tile/ohri-summary-tile.component.tsx
src/hts/home/summary-tile/hts-summary-tile.component.tsx

OHRI-148 Working

---

.github/workflows/node.js.yml
package.json

This is a fix for the Issue associated with Publish NPM

ohri-159-NPM, GitHub Actions fix Publish

---

README.md

This are additional commands to simplify development tasks

Updated README.md - Include Devtols and backend

---

src/components/top-nav/hiv-top-nav.component.tsx
src/forms/ohri-form.component.tsx
translations/en.json

Added Toaster notification, fixed Left Navigation color

OHRI-155-hts encouters-tab-hts-toaster

---

.gitignore
src/forms/_form.scss

This PR provides cleanups; spacing, adding `package-lock.json` to gitignore

Ohri 168 improved responsiveness

---

.github/workflows/node.js.yml

Remove the additional types for PRs

Fix 3x CI triggers

---

src/dasboard.scss

This is to fix for the 3rd time the issue with the Sidebar css that keeps being removed.
Also to test if the GitHub actions feed is working

Fix Sidebar Nav coulours

---

package-lock.json
src/forms/ohri-form.component.tsx
src/forms/submission-handlers/base-handlers.ts
src/hts/encounters-list/hts-overview-list.component.tsx
src/index.ts

[Ohri-168] Implement feedback

---

src/packages/hiv/forms/hts_retro/1.0.json

OHRI-176: Updated HTS Form (version 2.0) - Form Questions - Added toggleOptions for consent provided

OHRI-176: Updated HTS Form (version 2.0) - Form Questions - Added toggleOptions for consent provided

---

src/packages/hiv/forms/hts_retro/1.0.json

OHRI-176: Updated HTS Form (version 2.0) - Form Questions - eligibility, approach, pretest, TB/STI Screening, Testing completed

OHRI-176: Updated HTS Form (version 2.0) - Form Questions - eligibility, approach, pretest, TB/STI Screening, Testing completed

---

src/components/top-nav/hts-top-nav-links.ts
src/forms/components/inputs/multi-select/ohri-multi-select.component.tsx
src/forms/submission-handlers/base-handlers.ts
src/forms/test-forms/hts_service_enrolment_form-schema.ts

Initial work for the multi-select

ohri-189-form-engine-v2-multiselect-component

---

src/packages/hiv/forms/hiv_ct/service-enrollment.json

OHRI-179 Add Service enrolment JSON schema

---

src/forms/components/sidebar/ohri-form-sidebar.component.tsx
src/forms/ohri-form.component.tsx

This is to fix an issue on saving, also allow view mode for multi-select

OHRI-189 form-engine-v2-multiselect-component, fix issue on saving

---

src/forms/components/inputs/_input.scss
src/forms/components/inputs/unspecified/ohri-unspecified.component.tsx

This PR adds styling the unspecified section of the form.
**Screenshots**

[OHRI 187]: Required behaviour implementation styling

---

src/forms/_form.scss
src/forms/components/inputs/_input.scss
src/forms/components/inputs/radio/ohri-radio.component.tsx
src/forms/components/label/ohri-label.component.tsx
src/forms/components/page/_page.scss
src/forms/components/sidebar/ohri-form-sidebar.component.scss
src/forms/form-render/form-render-test.component.tsx
src/forms/submission-handlers/base-handlers.test.ts
src/forms/submission-handlers/base-handlers.ts
src/hts/care-and-treatment/care-and-treatment-list.component.tsx
src/hts/encounters-list/hts-overview-list.component.tsx
src/utils/forms-loader.test.ts
src/utils/forms-loader.ts
src/workspace/ohri-workspace-utils.ts
src/workspace/ohri-workspace.component.tsx

This PR adds styling fixes, alignments, and support to have the form open in full-screen view.

Ohri-103 form engine version 2 modification

---

src/dashboard.meta.tsx
src/dashboard.scss
src/index.ts

This PR Serves to ensure, active link and SideNav is ordered.

OHRI-202 - Fix, sidenav, include active links

---

src/dashboard.meta.tsx

This PR Serves to ensure, active link and SideNav is ordered.

Fix, sidenav, include active links, fix lint

---

src/forms/components/inputs/multi-select/ohri-multi-select.component.tsx
src/forms/components/inputs/toggle/ohri-toggle.component.tsx
src/forms/components/page/ohri-form-page.tsx
src/forms/components/section/ohri-form-section.component.tsx
src/forms/ohri-form.component.tsx
translations/en.json

This PR:
- Fixes the multi-select filter, on edit _mode_
- Reduces warnings in the console

OHRI-2020 - Fix handle for edit, remove console errors

---

src/dashboard.meta.tsx

This PR:
- Add the style for the SideNavs Routs

OHRI-202 - Fix route class

---

src/packages/covid/forms/case-report-form/1.0.json
src/packages/forms-registry.ts

Add all Covid case report form questions and package structure

OHRI-224 Add Covid case Form Question

---

src/packages/covid/forms/case-report-form/1.0.json

OHRI-225 Final touches on the schema

---

src/packages/covid/forms/case-report-form/1.0.json
src/packages/hiv/forms/care-and-treatment/service-enrolment/2.0.json

Add Service Enrolment Form behaviours

Feature/ohri 180 Service Enrolment form behaviours

---

src/packages/hiv/forms/care-and-treatment/service-enrolment/1.0.json
src/packages/hiv/forms/care-and-treatment/service-enrolment/2.0.json

Added patient identifier concept

OHRI-180 add patient identifier concept

---

src/components/empty-state/empty-state.component.tsx
src/components/modals/patient-list/add-patient-to-list-modal.component.tsx
src/components/tile/ohri-summary-tile-tablet.component.tsx
src/forms/components/inputs/multi-select/ohri-multi-select.component.tsx
src/hts-home/patient-list-cohort.component.tsx
src/hts/encounters-list/hts-overview-list.component.tsx
src/hts/patient-list/patient-list.component.tsx
translations/en.json

This PR is to address to the need to reduce clicks and add a given Patient to a List

OHRI-219 Home Screen patient list should provide action to add patient to list

---

src/components/patient-lists/patient-list-cohort.component.tsx

This PR is to fix this build failure ...

Fix import file

---

src/packages/hiv/forms/care-and-treatment/service-enrolment/1.0.json

OHRI-180 add behaviour to previous use of PrEP question

OHRI-180 add behaviour to previous use of PrEP question

---

src/components/patient-lists/patient-list-cohort.component.tsx
src/forms/components/page/ohri-form-page.tsx
src/forms/components/sidebar/ohri-form-sidebar.component.tsx

Reverts UCSF-IGHS/openmrs-esm-ohri#271

Revert "Styling[1] Sidebar and divider"

---

src/pages/drug-orders/encounter-list/drug-orders-encounter-list.component.tsx
src/pages/service-enrolment/encounter-list/service-enrolment-encounter-list.component.tsx

This PR covers the below scope

Fix Launch intent, coming soon page

---

src/packages/hiv/forms/care-and-treatment/clinical-visit/1.0.json

This PR is to Test the CD using CDN

Lars lemos dev trigger - Test CDN

---

.github/workflows/node.js.yml

This PR is to update the CI script trigger using _bash_

Lars lemos dev trigger 

---

src/components/empty-state/table-empty-state.component.tsx
src/components/patient-list-tabs/ohri-patient-list-tabs.scss
src/components/patient-lists/patient-list-cohort.component.tsx
src/components/patient-lists/patient-table.component.scss
src/forms/_form.scss
src/forms/components/page/_page.scss
src/forms/components/page/ohri-form-page.tsx
src/forms/components/sidebar/ohri-form-sidebar.component.scss
src/forms/ohri-form.component.tsx
src/ohri-home/ohri-home-component.tsx
src/pages/hts/home/patient-tabs/ohri-patient-tabs.scss
src/workspace/patient-list-workspace.scss
src/workspace/patient-list-workspace.tsx

**What does this PR do?**
This PR fixes stylings for the patient list styling, also fixes form responsiveness when minimized along with the scrolling issue.
**Screenshots**
**Issue**
PR is dependant on Patient-Chart [MF-707]

[OHRI-184] MFE Improvements

---

src/components/encounter-list/encounter-list.component.tsx
src/constants.ts
src/packages/hiv/forms/care-and-treatment/clinical-visit/1.0.json
src/pages/clinical-visit/encounter-list/clinical-visit-encounter-list.component.tsx
src/utils/ohri-forms-commons.ts

Jira: https://ohri.atlassian.net/browse/OHRI-227?atlOrigin=eyJpIjoiNjdjMTFkYWJjNzY0NGQzYjkzMzJmZjYxMjk0ZDBkN2QiLCJwIjoiaiJ9
Empty State
Encounters

OHRI-227 Encounter List Component

---

src/components/programme-switcher/ohri-programme-switcher-links.ts
src/covid/home/patient-list-tabs/covid-patient-list-tabs.component.tsx
src/covid/home/summary-tiles/covid-summary-tiles.component.tsx
src/index.ts
src/ohri-home/ohri-home-component.tsx
src/root.tsx

COVID-19 Home page initial configuration

OHRI-273: COVID-19 Home page

---

src/packages/covid/forms/case-assessment-form/1.0.json
src/packages/forms-registry.ts

Add COVID case assessment Form

OHRI-257 COVID case assessment Form

---

src/packages/covid/forms/lab-test-form/1.0.json
src/packages/forms-registry.ts

OHRI-258 COVID Lab test Form

---

src/packages/covid/forms/outcome-tracking-form/1.0.json
src/packages/forms-registry.ts

Add COVID Outcome tracking form

OHRI-260 Add COVID Outcome Tracking Form

---

src/packages/covid/forms/case-assessment-form/1.0.json

Delete 'date of assessment/encounter' - will use the encounter date

OHRI-257 Delete Date of assesssment question

---

package-lock.json
package.json
src/forms/form-render/form-render-test.component.tsx
src/forms/form-render/form-render.scss

OHRI-274 Form Render UX Improvements

---

src/components/encounter-list/encounter-list.component.tsx
src/components/ohri-form-launcher/ohri-form-laucher.componet.tsx
src/covid/pages/case-assessment.encounter-lists.tsx
src/hts/client-linkage/client-linkage-form-section.component.tsx
src/pages/hts/patient-list/patient-list.component.tsx

OHRI-256b Feature/ohri 271 covid patient chart

---

.github/workflows/node.js.yml
esm_packages.json
microfrontends.release.js

This PR covers the following work:

OHRI-315 Fix dependencies versions on Demo - 

---

src/constants.ts
src/covid/covid.scss
src/covid/dashboard.meta.tsx
src/covid/pages/case-assessment.encounter-lists.tsx
src/covid/pages/lab-results.encounter-list.tsx
src/packages/forms-registry.ts

OHRI-368 - Assessments section in the Patient Chart

---

src/constants.ts
src/covid/pages/covid-vaccinations.encounter-list.tsx

https://ohri.atlassian.net/browse/OHRI-373

OHRI-373 Add vaccination section

---

package.json
src/components/ohri-form-launcher/ohri-form-launcher.component.tsx
src/forms/components/encounter/ohri-encounter-form.tsx
src/forms/components/inputs/fixed-value/ohri-fixed-value.component.tsx
src/forms/form-render/form-render-test.component.tsx
src/forms/ohri-form.component.tsx
src/forms/registry/registry.ts
src/forms/types.ts
src/utils/forms-loader.ts

OHRI-359, 355 Add fixed-value type, render, markdown, intent

---

src/forms/components/page/ohri-form-page.tsx
src/forms/components/section/ohri-form-section.component.tsx
src/forms/ohri-form.component.tsx
src/forms/types.ts
src/utils/forms-loader.test.ts
src/utils/forms-loader.ts

This PR covers the below scope:

Larslemos working v2

---

src/forms/components/encounter/ohri-encounter-form.tsx
src/forms/components/page/ohri-form-page.tsx
src/forms/components/section/ohri-form-section.component.tsx
src/forms/form-render/form-render-test.component.tsx
src/forms/types.ts
src/utils/forms-loader.test.ts
src/utils/forms-loader.ts

This PR covers the below scope:

Add fixed value, intent inheritance'

---

src/components/encounter-list/encounter-list.component.tsx
src/components/ohri-form-launcher/ohri-form-launcher.component.tsx
src/components/overflow-menu-button/ohri-overflow-menu.component.tsx
src/constants.ts
src/covid/pages/lab-results.encounter-list.tsx
src/packages/covid/forms/lab-order-cancellation/1.0.json
src/packages/covid/forms/lab-order-form/1.0.json
src/packages/covid/forms/lab-result-form/1.0.json
src/utils/forms-loader.ts

This PR Covers the below scope:

OHRI-365, OHRI-368 Feature/ohri 344 covid patient chart 2

---

src/forms/components/inputs/_input.scss
src/forms/components/section/ohri-form-section.component.tsx

OHRI-324 form validation errors on text and textarea labels

---

src/covid/pages/case-assessment.encounter-lists.tsx
src/packages/covid/forms/case-form/1.0.json

Full covid case assessment to show outcome and not lab order.

Full covid case assessment to show outcome and not lab order.

---

src/components/encounter-list/encounter-list.component.tsx
src/covid/pages/case-assessment.encounter-lists.tsx
src/covid/pages/lab-results.encounter-list.tsx

This is a draft PR to clean up the encounter list component actions with multiple forms

OHRI-443 reusable encounter list actions

---

src/packages/covid/forms/lab-test-form/1.0.json
src/packages/covid/forms/sample-collection-form/1.0.json

OHRI-448: Lab Test - Pending lab orders

OHRI-448: Lab Test - Pending lab orders

---

src/components/encounter-list/encounter-list.component.tsx
src/components/ohri-form-launcher/ohri-form-launcher.component.tsx
src/components/overflow-menu-button/ohri-overflow-menu.component.tsx
src/constants.ts
src/covid/pages/lab-results.encounter-list.tsx
src/packages/covid/forms/lab-order-cancellation/1.0.json
src/packages/covid/forms/lab-order-form/1.0.json
src/packages/covid/forms/lab-result-form/1.0.json
src/packages/covid/forms/sample-collection-form/1.0.json
src/utils/forms-loader.ts

Sync Feature/ohri 344 covid patient chart 2 to Dev

---

src/components/overflow-menu-button/ohri-overflow-menu.component.tsx
src/covid/pages/lab-results.encounter-list.tsx

Fix Add button ..., add Cancel Action to Pending

---

src/forms/components/encounter/ohri-encounter-form.tsx
src/forms/components/inputs/markdown/ohri-markdown.component.tsx
src/forms/components/page/ohri-form-page.tsx
src/forms/components/section/ohri-form-section.component.tsx
src/forms/registry/registry.ts
src/forms/types.ts
src/utils/forms-loader.ts

OHRI-355 Remove unused code, update parser for question type

---

src/components/encounter-list/encounter-list.component.tsx
src/packages/covid/forms/case-assessment-form/1.0.json

- OHRI-478: Fix issue with form title when working with multiple forms
- OHRI-369: COVID Assesment Form

OHRI-369 & OHRI-478

---

src/packages/covid/forms/case-assessment-form/1.0.json
src/packages/covid/forms/case-form/1.0.json

OHRI-370, OHRI-447

---

src/components/encounter-list/encounter-list.component.tsx
src/constants.ts
src/covid/pages/case-assessment.encounter-lists.tsx
src/workspace/ohri-workspace-utils.ts

Reverts UCSF-IGHS/openmrs-esm-ohri#654

Revert "Feature/ohri 452 overall UI" - To fix Lint issue

---

src/forms/components/inputs/multi-select/ohri-multi-select.component.tsx

https://ohri.atlassian.net/jira/software/projects/OHRI/boards/1?selectedIssue=OHRI-436

OHRI-436: Multi-Select input field should show the label selected

---

package-lock.json
src/forms/ohri-form.component.tsx
src/forms/ohri-form.scss
src/ohri-patient-dashboards-config.json

OHRI-508 save cancel buttons to form bottom

---

src/components/modals/patient-list/add-patient-to-list-modal.component.tsx
src/components/patient-lists/patient-list-cohort.component.tsx
src/pages/hts/home/patient-tabs/ohri-patient-tabs.component.tsx
src/pages/hts/patient-list/patient-list.component.tsx

@samuelmale to the PR one of the Following:
Either a paragraph like these I did for @ODORA0  @pirupius 
This PR covers the following:
or the link for the ticket to facilitate review. 
This applies to the all Team. Lets build a good culture. 
Thanks.

OHRI-611: Remove 'post-test counselling' list from 'pre-test' section

---

src/components/patient-lists/patient-list-cohort.component.tsx
src/hts/home/patient-tabs/ohri-patient-tabs.component.tsx
src/pages/hts/home/patient-tabs/ohri-patient-tabs.component.tsx
src/utils/ohri-forms-commons.ts
src/workspace/ohri-workspace-utils.ts

As we wait for Brandon's input on this([thread](https://openmrs.slack.com/archives/CHP5QAE5R/p1645470609157969), for now let's have this.

OHRI-337: Provisional support for deep linking

---

package-lock.json
src/forms/ohri-form.scss

OHRI-602 OHRI 628 OHRI 626 Feature/ohri 452 overall UI

---

package-lock.json
src/forms/ohri-form.component.tsx
src/forms/ohri-form.scss
src/root.scss

OHRI-452 hide patient header when form is minimized

---

.github/workflows/node.js.yml

Add action to export concepts to csv file.

Add action to export concepts to csv file.

---

src/components/patient-banner/patient-banner.component.tsx
src/forms/ohri-form.component.tsx
src/forms/overrides.scss

This is the current Patient Banner on the Form:
The objective is to make this an option Overflow Button, since for this scenario, the actions don't apply for our context. 
https://issues.openmrs.org/browse/O3-1154?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D

OHRI-509 Add hideActions optional param, redefine logic

---

src/constants.ts
src/packages/forms-registry.ts
src/packages/hiv/forms/care-and-treatment/art-therapy/1.0.json
src/pages/program-management/tabs/art-therapy-tab.component.tsx

OHRI 666 ART Therapy form added

OHRI 666 ART Therapy form added - Feature/ohri 511 care and treatment sprint15 demo 8

---

src/packages/forms-registry.ts
src/pages/program-management/tabs/art-therapy-tab.component.tsx

OHRI 666 Added ART Therapy form - fixed bug in form registry

OHRI 666 Added ART Therapy form Feature/ohri 511 care and treatment sprint15 demo 8

---

src/pages/visits/tabs/clinical-visit-tab.component.tsx

OHRI-706 Add appointment reason placeholder for clinical visit Form

---

src/components/patient-lists/patient-list-cohort.component.tsx

- Loads latest encounter for all patients
- Adds table loader

(fix) Improve cohort list widget

---

src/components/modals/patient-list/add-patient-to-list-modal.component.tsx
src/components/patient-lists/patient-list-cohort.scss

Before:
Demo (After):
https://user-images.githubusercontent.com/15266028/158963196-f1b8b7b3-b191-43a9-bf8f-901b121c6aa1.mov

OHRI-733 remove focused blue border on opening cohort overflow menu

---

src/packages/forms-registry.ts
src/packages/hiv/forms/care-and-treatment/art-therapy/1.0.json

Removed rules on notes to allow form save without notes.

OHR-781 ART Therapy form not saving

---

packages/esm-hiv-app/src/forms/care-and-treatment/service-enrolment/1.1.json

HIV Enrollment Form: re-enroll business rules updated

OHRI-790 HIV Enrollment Form: re-enroll business rules updated

---

yarn.lock

Manually resolve, form-engine lock version

---

packages/esm-commons-lib/src/components/encounter-tile/encounter-tile.component.tsx
packages/esm-commons-lib/src/components/encounter-tile/encounter-tile.scss
packages/esm-commons-lib/translations/en.json
packages/esm-hiv-app/src/constants.ts
packages/esm-hiv-app/src/views/service-summary/encounter-list/service-summary-encounter-list.component.tsx

This PR has the place Holders for the following Scope:

OHRI-966 OHRI-967 Feature/ohri 511 care and treatment s27 d20

---

package.json
packages/esm-commons-lib/src/components/ohri-home/ohri-home-component.tsx
packages/esm-commons-lib/src/components/ohri-home/ohri-home.scss
packages/esm-commons-lib/src/components/tile/ohri-programme-summary-tiles.component.tsx
packages/esm-commons-lib/src/components/tile/ohri-programme-summary-tiles.scss
packages/esm-covid-app/src/views/dashboard/summary-tiles/covid-summary-tiles.component.tsx
yarn.lock

OHRI-1087 fixes dashboard UI

---

packages/esm-ohri-pmtct-app/src/forms/labour-and-delivery/1.0.json

OHRI-1127 ART Prompt for ART initiation if tested during this visit @delivery resolved on form

---

.github/workflows/node.js.yml

This PR is a trigger for changes in NVM backend config

Update comment to Trigger NVM changes

---

packages/esm-commons-lib/src/components/expandable-list-widget/expandable-list.component.tsx
packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/current-pregnancy.component.tsx

OHRI-1174 make name in family widget clickable

---

packages/esm-ohri-pmtct-app/src/api/api.ts
packages/esm-ohri-pmtct-app/src/api/types.ts
packages/esm-ohri-pmtct-app/src/constants.ts
packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/previous-pregnancies.component.tsx

OHRI-1186 adds anc visits to previous pregnancies

---

packages/esm-commons-lib/src/api/api.ts
packages/esm-commons-lib/src/components/card-summary/card-summary.component.tsx
packages/esm-ohri-pmtct-app/src/constants.ts
packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/current-pregnancy.component.tsx

OHRI-1198 Add Total ANC visit count to Maternal Summary

---

packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/current-pregnancy.component.tsx

Screenshots in this [CARD](https://ohri.atlassian.net/browse/OHRI-1212)

OHRI-1212 Mother HIV status and EDD populated in the summary

---

packages/esm-commons-lib/src/components/expandable-list-widget/expandable-list.component.tsx
packages/esm-ohri-pmtct-app/src/api/api.ts
packages/esm-ohri-pmtct-app/src/constants.ts
packages/esm-ohri-pmtct-app/src/views/mch-summary/mch-summary.component.tsx
packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/current-pregnancy.component.tsx
packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/hiv-exposed-infant.component.tsx
packages/esm-ohri-pmtct-app/translations/en.json

OHRI-1197 adding concepts to infant summary

---

packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/current-pregnancy.component.tsx

This PR Covers the below scope:

OHRI-1211 OHRI-1210 Visits added under the Maternal Summary and Child Summary 

---

packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/current-pregnancy.component.tsx
packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/hiv-exposed-infant.component.tsx

OHRI-1197 fixes to hiv infant next appointment

---

packages/esm-ohri-pmtct-app/src/constants.ts
packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/hiv-exposed-infant.component.tsx

OHRI-1242 Visit date data fetched under the visits section

---

packages/esm-ohri-pmtct-app/src/root.scss
packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/current-pregnancy.component.tsx

OHRI-1239 MNCH Mother & Child Summary Widgets aligned

---

packages/esm-ohri-core-app/src/index.ts
packages/esm-ohri-core-app/src/registration-config.json

Revised wordings in the 'Relationship' section

---

package.json
packages/esm-ohri-pmtct-app/src/form-entry/forms/infant-postnatal/1.0.json
packages/esm-ohri-pmtct-app/src/form-entry/forms/mother-postnatal/1.0.json

OHRI-1323 OHRI-1323 Next visit date validation in PNC form

---

packages/esm-ohri-core-app/locales/en/translation.json
packages/esm-ohri-core-app/locales/fr/translation.json
packages/esm-ohri-core-app/src/ohri-dashboard/side-menu/ohri-dashboard-side-nav.component.tsx
packages/esm-ohri-core-app/translations/en.json

OHRI-1364 rename ohri dashboards to programs

---

packages/esm-ohri-core-app/src/ohri-esm-and-dashboards-config.json

OHRI-1367 remote visit actions from patient banner

---

packages/esm-ohri-core-app/src/ohri-esm-and-dashboards-config.json

OHRI-1366 notes and forms hidden from patient chart right nav

---

packages/esm-ohri-core-app/src/ohri-esm-and-dashboards-config.json
yarn.lock

OHRI-1343 remove dispensing link from app menu

---

packages/esm-ohri-core-app/src/ohri-core-config.ts

- Pharmacy icon renamed to Dispensing
- Indentation fixed

OHRI-1405: Pharmacy icon renamed to Dispensing

---

packages/esm-hiv-app/src/dashboard.meta.tsx

HTS displayed in full (HIV Testing Services)

OHRI-1421: HTS displayed in full (HIV Testing Services)

---

packages/esm-cervical-cancer-app/src/index.ts
packages/esm-covid-app/src/index.ts
packages/esm-hiv-app/src/index.ts
packages/esm-ohri-core-app/src/index.ts
packages/esm-ohri-pmtct-app/src/index.ts

Add order to ohri specific patient chart links

---

packages/esm-ohri-core-app/src/root.scss

OHRI-1362 overrides widget max-width in patient chart

---

.github/workflows/node.js.yml

Infant PNC tab renamed to HIV Exposed Infant

OHRI-1418: Infant PNC tab renamed to HIV Exposed Infant

---

packages/esm-ohri-pmtct-app/src/index.ts

- Added MNCH to left perspective.

OHRI-1842: Added MNCH to left perspective

---

packages/esm-ohri-pmtct-app/src/views/child-health/tabs/infant-postnatal-care.component.tsx

Fixes exploding network requests while on the Infant Postnatal Care DB

Disable fetching of the mother's name in the infant postnatal care

---

package.json
packages/esm-commons-lib/src/components/encounter-list/encounter-list.component.tsx
packages/esm-commons-lib/src/components/encounter-list/helpers.ts
packages/esm-commons-lib/src/hooks/useEncounterRows.ts
packages/esm-commons-lib/src/hooks/useFormJsonSchemas.ts
packages/esm-commons-lib/src/hooks/useFormsJson.ts
packages/esm-commons-lib/src/hooks/usePatientDeathStatus.ts
packages/esm-ohri-pmtct-app/src/views/child-health/tabs/infant-postnatal-care.component.tsx

This PR fixes:
- The recently reported performance issues within the EncounterList widget. (Exploding network requests)
- The data list is updated instantly on saving an encounter
- Misc improvements

Revamping encounter-list for better performance

---

package.json
packages/esm-commons-lib/src/components/patient-lists/patient-list.component.tsx
packages/esm-commons-lib/src/hooks/usePatientList.tsx

In summary, this PR improves the performance of the Patient List widget.

Revamp Patient List

---

packages/esm-commons-lib/src/components/encounter-tile/encounter-tile.scss

OHRI-1479 encounter tile responsiveness

---

packages/esm-covid-app/src/routes.json
packages/esm-ohri-core-app/src/ohri-dashboard/ohri-dashboard.component.tsx
packages/esm-ohri-core-app/src/routes.json
packages/esm-ohri-pmtct-app/src/routes.json

**Summary**
- Minor tweaks to the ohri-dashboard component
- Fix home
- Fix MNCH
- Tackle covid db (Requires a little more work, will be addressed in a followup PR)
**Attachments**

Fix home and MNCH Clinical dashboards

---

packages/esm-ohri-pmtct-app/src/views/maternal-health/tabs/antenatal-care.component.tsx
packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/hiv-exposed-infant.component.tsx

PTracker Patient Chart
-ART Unique Number removed from ANC list
-Updated a form name in the hiv exposed infant

OHRI-1563: ART Unique Number and ART start date removed from ANC list

---

packages/esm-form-render-app/src/render/form-render.scss
packages/esm-form-render-app/src/render/forms-render-test.component.tsx

The encounter Uuid text field allows to open a form in edit mode in form render.

Introduce Encounter Uuid field to form render

---

packages/esm-form-render-app/src/render/forms-render-test.component.tsx

This fixes the following bugs: 
- Form not validating without browser refresh.
- Loading new form not replacing old form.
- Added fixed value as a rendering option.
- Added question ids to identify the responses on the console.

ohri-form-validator-update: updates and bug fixes

---

packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/current-pregnancy.component.tsx

Placeholders for the tiles OHRI-1680

---

packages/esm-form-render-app/src/render/form-render.scss

Fix issue where the Form's footer doesn't perfectly fit in the container

---

packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/current-pregnancy.component.tsx

Fix Type error: cannot read properties of null on the MNCH Summary

OHRI-1641: Fix Type error: cannot read properties of null on the MNCH Summary

---

packages/esm-ohri-pmtct-app/src/constants.ts
packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/hiv-exposed-infant.component.tsx

The child’s HIV status to display the 'Final Test Results'

Update- The child’s HIV status to display the 'Final Test Results'

---

packages/esm-cervical-cancer-app/src/dashboard.meta.tsx
packages/esm-cervical-cancer-app/src/routes.json
packages/esm-covid-app/src/dashboard.meta.tsx
packages/esm-covid-app/src/routes.json
packages/esm-hiv-app/src/dashboard.meta.tsx
packages/esm-hiv-app/src/routes.json
packages/esm-ohri-core-app/src/root.scss
packages/esm-ohri-pmtct-app/src/dashboard.meta.tsx
packages/esm-ohri-pmtct-app/src/routes.json

Pending https://github.com/openmrs/openmrs-esm-patient-chart/pull/1311

OHRI-1440 add fullWidth meta to support full width patient chart widgets

---

packages/esm-ohri-pmtct-app/src/api/api.ts
packages/esm-ohri-pmtct-app/src/views/summary-tabs/maternal-child-summary-tiles.component.tsx

- Count the number of unique women who delivered from the start of the fiscal year (1 April 2023) up to the current date.

OHRI-1512: Total deliveries updated on the Labour & Delivery tile

---

packages/esm-ohri-core-app/src/ohri-dashboard/dispensing/dispensing-dashboard.component.tsx
packages/esm-ohri-core-app/src/routes.json

- Launch Dispensing from the perspective

OHRI-1808: Unable to launch Dispensing from the perspective

---

package.json
packages/esm-commons-lib/package.json
packages/esm-form-render-app/src/render/forms-render-test.component.tsx
packages/esm-ohri-pmtct-app/src/views/summary-tabs/maternal-child-summary-tiles.component.tsx
yarn.lock

This explicitly bumps the @openmrs/esm-patient-common-lib in OHRI as a solution to: https://ohri.atlassian.net/browse/OHRI-1824

(chore) Properly setup patient commons and fix lint errors

---

packages/esm-commons-lib/src/components/patient-list-cohort/patient-list-cohort.component.tsx

This fixes the issue with the patient list component not loading.

OHRI-1882: Fix HIV Care and Treatment Dashboard on the home screen

---

.github/workflows/node.js.yml

Update node.js.yml - Change CI/CD user ssh private key

Update node.js.yml - Change CI/CD user ssh private key

---

packages/esm-hiv-app/src/constants.ts
packages/esm-hiv-app/src/views/program-management/tabs/hiv-enrolment-tab.component.tsx

OHRI-1879 Populate the correct HIV Enrollment data on the list

---

packages/esm-commons-lib/src/utils/encounter-list-utils.ts

This ticket allows the date to be formatted according to the user's current locale
https://github.com/UCSF-IGHS/openmrs-esm-ohri/assets/12844964/2f8aa5b9-2bdb-49f3-bade-097e7071a3ce

OHRI-1896 Format date according to locale

---

packages/esm-ohri-pmtct-app/src/dashboard.meta.tsx
packages/esm-ohri-pmtct-app/src/index.ts

ANC and L&D & PNC  entries for male >10 years clients discontinued
https://github.com/UCSF-IGHS/openmrs-esm-ohri/assets/130601439/5d4ebfad-2bd8-48ea-8bc5-51e4cdde50e8

OHRI-1893:ANC and L&D & PNC  entries for male clients discontinued

---

packages/esm-cervical-cancer-app/src/constants.ts
packages/esm-cervical-cancer-app/src/views/cacx-visits/Tabs/cacx-treatment.component.tsx
packages/esm-commons-lib/src/utils/encounter-list-utils.ts

https://github.com/UCSF-IGHS/openmrs-esm-ohri/assets/12844964/2f4448f4-4df1-4742-81cf-0258c2bed903

OHRI-1880 Show the screening results on the CaCx Treatment list

---

packages/esm-covid-app/src/views/lab-results.encounter-list.tsx

The Add dropdown showed all intents of the forms and thus I added the embedded intents in the excludeIntents array of the encounterList prop

OHRI-1965 Show Lab Order and Lab Result in Add action

---

packages/esm-hiv-app/src/views/visits/tabs/clinical-visit-tab.component.tsx

OHRI-1881 Amend the next appointment date format & remove appointment reason on the clinical visit list

---

yarn.lock

OHRI-1966 FE Bump

---

packages/esm-hiv-app/src/constants.ts
packages/esm-hiv-app/src/views/hiv-testing-services/tab-list/hts-overview-list.component.tsx

OHRI 1959: Update date of HIV test to read from encounter

---

packages/esm-covid-app/src/dashboard.meta.tsx
packages/esm-covid-app/src/routes.json

OHRI-1964 COVID-19 Cases" title missing in the COVID Programme

---

packages/esm-tb-app/README.md
packages/esm-tb-app/package.json
packages/esm-tb-app/src/constants.ts
packages/esm-tb-app/src/dashboard.meta.tsx
packages/esm-tb-app/src/dashboard.scss
packages/esm-tb-app/src/declarations.d.tsx
packages/esm-tb-app/src/index.ts
packages/esm-tb-app/src/root.scss
packages/esm-tb-app/src/routes.json
packages/esm-tb-app/src/setupTests.ts
packages/esm-tb-app/src/views/common.scss
packages/esm-tb-app/translations/en.json
packages/esm-tb-app/tsconfig.json
packages/esm-tb-app/webpack.config.js
yarn.lock

Base PR for TB microfrontend. Other building blocks will be added on top of this
https://ohri.atlassian.net/browse/OHRI-2016

OHRI-2016 TB microfrontend

---

.github/workflows/node.js.yml
frontend/ohri-config.json

Remove patient chart nav links that were previouslt excluded

(chore) remove excluded patient chart configs

---

frontend/spa-build-config.json

Biometric and Vitals have been merged into the Vitals esm so there's no need to keep this package in the spa build

(chore) remove biometrics esm from spa-build-config.json

---

packages/esm-tb-app/src/dashboard.meta.tsx
packages/esm-tb-app/src/views/treatment-and-follow-up/tb-treatment-follow-up.component.tsx
packages/esm-tb-app/translations/en.json

OHRI-1994 MINOR changes-after-review

---

packages/esm-tb-app/src/dashboard.meta.tsx
packages/esm-tb-app/translations/en.json

Minor TB Typo Changes

---

packages/esm-ohri-pmtct-app/src/post-submission-actions/mother-child-linkage-action.ts

OHRI-1963 Code clean up

---

packages/esm-commons-lib/src/components/empty-state/empty-state.scss
packages/esm-commons-lib/src/components/encounter-list/encounter-list.scss
packages/esm-tb-app/src/views/patient-summary/tb-patient-summary.component.tsx

TB Cases Encounter list
https://ohri.atlassian.net/browse/OHRI-2013

OHRI-2013 tb previous cases table

---

packages/esm-tb-app/src/views/treatment-and-follow-up/tb-treatment-follow-up.component.tsx

(Fix) FollowUp table List Should Show Form Metadata

---

packages/esm-tb-app/src/views/treatment-and-follow-up/tb-treatment-follow-up.component.tsx
packages/esm-tb-app/translations/en.json

Fix label on Follow-up list

---

packages/esm-commons-lib/src/components/cohort-patient-list/cohort-patient-list.component.tsx
packages/esm-commons-lib/src/components/cohort-patient-list/helpers.tsx
packages/esm-commons-lib/src/components/patient-list-tabs/ohri-patient-list-tabs.component.tsx
packages/esm-tb-app/src/views/dashboard/patient-list-tabs/tb-patient-list-tabs.component.tsx
packages/esm-tb-app/translations/en.json

- All the actions are operational as required.
Actions

OHRI-2002: Updates on the All TB Clients Table in the TB Treatment dashboard.

---

packages/esm-tb-app/src/views/program-management/tabs/mdr-tb.component.tsx

OHRI-2036: Remove-TypeError-Cannot-read-properties-of-null-(reading-'obs')

---

packages/esm-tb-app/src/views/program-management/tabs/mdr-tb.component.tsx

We have to check the latest encounter and see if there are any obs for the treatment outcome, but when there is no encounter created at all for a patient then we are not able to enter a new form for a new patient because the state will always stay truthy until we have an obs for the treatment outcome. This needed some refactoring on the state and to check if the result length was totally zero

Refactor state in Mdr-tb encounterList component

---

README.md
lerna.json
packages/esm-cervical-cancer-app/package.json
packages/esm-commons-lib/package.json
packages/esm-covid-app/package.json
packages/esm-form-render-app/package.json
packages/esm-hiv-app/package.json
packages/esm-ohri-core-app/package.json
packages/esm-ohri-pmtct-app/package.json
packages/esm-tb-app/package.json
packages/esm-tb-app/src/views/dashboard/patient-list-tabs/tb-patient-list-tabs.component.tsx
yarn.lock

- Updates patient commons peer dependency
- Bumps version
- Adds TB to readme

(chore) release 2.1.x

---

package.json
packages/esm-cervical-cancer-app/package.json
packages/esm-commons-lib/package.json
packages/esm-covid-app/package.json
packages/esm-form-render-app/package.json
packages/esm-hiv-app/package.json
packages/esm-ohri-core-app/package.json
packages/esm-ohri-pmtct-app/package.json
packages/esm-tb-app/package.json
yarn.lock

This builds on top of work previously done within esm-core https://github.com/openmrs/openmrs-esm-core/pull/774 
N/A
https://ohri.atlassian.net/browse/OHRI-2034

OHRI-2034 make swr peer dependency

---

packages/esm-covid-app/src/index.ts

This PR updates esm-covid-app packages to synchronously load pages and extensions

OHRI-2045 COVID - Update package index.ts to syncronously load pages and extensions

---

__mocks__/encounter-tile.mock.ts
__mocks__/obs-base-table.mock.ts

This PR add encounter tile related mock data to support tests

(chore) Add encounter tile related mock data

---

__mocks__/obs-base-table.mock.ts
packages/esm-commons-lib/src/components/data-table/o-table.component.tsx
packages/esm-commons-lib/src/components/data-table/o-table.test.tsx

Add unit tests for OTable in commons lib
Updated table size according to carbon

OHRI-2079 Add unit tests for OTable in commons lib

---

packages/esm-commons-lib/src/components/tile/ohri-summary-tile.test.tsx

Tests for OHRI summary tile component

OHRI-2086 Add unit tests for ohri summary tile in commons lib

---

packages/esm-commons-lib/src/components/tile/ohri-summary-tile.test.tsx

(fix) Update imports on summary tile test

---

packages/esm-ohri-pmtct-app/src/config-schema.ts
packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/current-pregnancy.component.tsx

This is a post-config migration fix for the MCH summary. This was caused by a config key that wasn't being detected and in this case wasn't necessary

(fix) fixes error with wrong config on mch summary

---

packages/esm-tb-app/src/tb-helper.ts
packages/esm-tb-app/src/views/patient-summary/tb-patient-summary.component.tsx
packages/esm-tb-app/src/views/program-management/tabs/mdr-tb.component.tsx

This PR fixes the issue of some values not displaying on the TB Summary page.

OHRI-2090 OHRI-2094 fix tb summary

---

packages/esm-commons-lib/src/components/tile/ohri-programme-summary-tiles.test.tsx

Add unit tests for ohri programme summary tile in commons lib

OHRI-2087: Add unit tests for ohri programme summary tile in commons lib

---

packages/esm-commons-lib/src/components/patient-table/patient-table.test.tsx

Add unit tests for patient table in commons lib

OHRI-2084: Add unit tests for patient table in commons lib

---

package.json
packages/esm-cervical-cancer-app/package.json
packages/esm-commons-lib/package.json
packages/esm-covid-app/package.json
packages/esm-form-render-app/package.json
packages/esm-hiv-app/package.json
packages/esm-ohri-core-app/package.json
packages/esm-ohri-pmtct-app/package.json
packages/esm-tb-app/package.json

(chore) Bump version 2.2.0

---

.github/workflows/node.master.js.yml

Added auth for publish to npm (#1775)

---

packages/esm-tb-app/src/dashboard.meta.tsx
packages/esm-tb-app/src/index.ts
packages/esm-tb-app/src/routes.json
packages/esm-tb-app/src/views/tpt/patient-summary/patient-summary.component.tsx
packages/esm-tb-app/translations/en.json

Adds the patient summary in the TPT Program Menu

OHRI-2117 Add TPT program menu

---

packages/esm-tb-app/src/config-schema.ts
packages/esm-tb-app/src/views/tpt/patient-summary/patient-summary.component.tsx
packages/esm-tb-app/translations/en.json

Populate the Recent TPT tiles on the TPT patient summary board
https://github.com/UCSF-IGHS/openmrs-esm-ohri/assets/130601439/5d2e8875-8c82-49df-9d56-955541a3b603

OHRI-2119: Populate the Recent TPT tiles on the TPT patient summary board

---

packages/esm-tb-app/src/tb-helper.ts
packages/esm-tb-app/src/views/tpt/program-management/tabs/tpt-enrolment.component.tsx

The hyperlink on the TPT Enrolment empty table list was redirecting to the Outcome Form rather than the TPT Case Enrolment form. This simple PR fixes that

Fix hyperlink on empty table list

---

packages/esm-tb-app/src/views/tpt/patient-summary/patient-summary.component.tsx

This PR add the visits table in the patient summary

OHRI-2130 Patient Visits table on the TPT patient summary

---

packages/esm-commons-lib/package.json
packages/esm-form-render-app/package.json
yarn.lock

(Chore) Bump FE Version

---

packages/esm-ohri-pmtct-app/package.json
yarn.lock

https://github.com/UCSF-IGHS/openmrs-esm-ohri/assets/19629227/20d94688-9051-44a7-963d-528bf747ff4a

Restore the MNCH Module in the Clinical Views

---

packages/esm-ohri-pmtct-app/src/views/maternal-health/tabs/labour-delivery.component.tsx
packages/esm-ohri-pmtct-app/src/views/maternal-health/tabs/postnatal-care.component.tsx

Maternal visits list should indicate HIV Test status not HIV test result
https://github.com/UCSF-IGHS/openmrs-esm-ohri/assets/19629227/1f25c7fa-9aa2-4cbf-aaea-8b9c45e88d1a

OHRI-1916 Replace HIV test result with status on Maternal visits 

---

package.json
yarn.lock

Removes extra spacing that was introduced in a previous PR

(chore) remove spacing in package name

---

packages/esm-commons-lib/src/workspace/ohri-workspace-utils.ts
yarn.lock

(feat) Upgrade patient commons lib, fix workspace isse

---

packages/esm-commons-lib/package.json
packages/esm-ohri-pmtct-app/package.json
yarn.lock

(feat)Upgrade patient commons lib, fix workspace issue

---

packages/esm-commons-lib/package.json
packages/esm-form-render-app/package.json
packages/esm-ohri-pmtct-app/package.json
yarn.lock

Changed to  the form-engine version for form-render-app

---

packages/esm-ohri-pmtct-app/package.json
packages/esm-ohri-pmtct-app/src/config-schema.ts
packages/esm-ohri-pmtct-app/src/post-submission-actions/art-linkage-action.ts
packages/esm-ohri-pmtct-app/src/post-submission-actions/current-ptracker-action.ts
packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/hiv-exposed-infant.component.tsx
yarn.lock

Error 400 appears whenever you save the various forms - ANC, L&D etc
Uploading Screen Recording 2024-03-04 at 9.13.09 PM.mov…

OHRI-2156:Remove error 400 on ohri-namibia-working

---

e2e/specs/registration-test.spec.ts

Update new homepage path on playwright

(fix) Update new homepage path on playwright

---

packages/esm-opd-app/package.json
packages/esm-opd-app/src/index.ts
yarn.lock

opd updates

---

packages/esm-ohri-pmtct-app/src/index.ts

(fix) Fix wrong import in pmtct link

---

packages/esm-ohri-pmtct-app/package.json

removed form engine dependency from the pmtct app

---

packages/esm-commons-lib/src/components/encounter-list/encounter-list.component.tsx
packages/esm-ohri-pmtct-app/src/config-schema.ts

Fix empty button intents on encounter list

---

yarn.lock

Bumping form-engine version to `1.0.0-pre.589`

Bumping form engine version

---

packages/esm-commons-lib/src/components/encounter-list/encounter-list.component.tsx
packages/esm-commons-lib/src/components/encounter-list/helpers.ts

(refactor) Add form name instead of form uuid in launch form function

---

packages/esm-opd-app/package.json
yarn.lock

update opd package version to  version `7.1.0-5`

update opd package version

---

packages/esm-ohri-pmtct-app/src/views/mch-summary/tabs/current-pregnancy.component.tsx

Populate the missing MNCH data

OHRI-2040: Populate MNCH Summary data

---

packages/esm-cervical-cancer-app/package.json
packages/esm-commons-lib/package.json
packages/esm-covid-app/package.json
packages/esm-form-render-app/package.json
packages/esm-hiv-app/package.json
packages/esm-ohri-core-app/package.json
packages/esm-ohri-pmtct-app/package.json
packages/esm-opd-app/package.json
packages/esm-tb-app/package.json

Bumping v2.2.0 -> 2.3.1

---

packages/esm-commons-lib/package.json
packages/esm-form-render-app/package.json
yarn.lock

- Fixed form renderer linking issues

(fix) Fixed form renderer linking issues

---

packages/esm-cervical-cancer-app/src/dashboard.meta.tsx
packages/esm-cervical-cancer-app/src/index.ts

- Hide the `cervical cancer` for all male patients and young females
- Hidden for young females and all males
- https://ohri.atlassian.net/browse/OHRI-2230

(fix) Cervical Cancer navigation should not be visible for Male and Children patients.

---

.github/workflows/node.dev.js.yml

Update node.dev.js.yml - remove `release` workflow trigger in dev branch

---

packages/esm-cervical-cancer-app/src/views/cacx-visits/cacx-config.json
packages/esm-cervical-cancer-app/src/views/cacx-visits/cacx-visits-services.component.tsx
packages/esm-commons-lib/src/utils/schema-manipulation.ts

Use concept keys from the default schema

---

packages/esm-commons-lib/src/utils/patient-list-tabs-config-builder.ts
packages/esm-covid-app/src/covid/dashboard/patient-list-tabs/covid-patient-list-schema-config.json
packages/esm-covid-app/src/covid/dashboard/patient-list-tabs/covid-patient-list-tabs.component.tsx

Implement covid homepage dashboard workflows

OHRI-2252 Implement covid homepage dashboard workflows

---

packages/esm-commons-lib/src/api.resource.ts
packages/esm-commons-lib/src/components/cohort-patient-list/cohort-patient-list.component.tsx
packages/esm-commons-lib/src/components/cohort-patient-list/helpers.tsx
packages/esm-commons-lib/src/components/patient-list-tabs/ohri-patient-list-tabs.component.tsx
packages/esm-commons-lib/src/components/patient-table/patient-table.component.tsx
packages/esm-commons-lib/src/components/patient-table/patient-table.scss
packages/esm-commons-lib/src/components/patient-table/patient-table.test.tsx
packages/esm-commons-lib/src/constants.ts
packages/esm-commons-lib/src/utils/patient-list-tabs-config-builder.ts
packages/esm-covid-app/src/covid/dashboard/patient-list-tabs/covid-patient-list-schema-config.json

- Fix breaking cohort list due to infinite loop

OHRI-2256 Fix breaking cohort list due to infinite loop

---

packages/esm-commons-lib/src/components/cohort-patient-list/helpers.tsx
yarn.lock

Fixed Workspace window error to use WorkspaceContainer

(fix) Fixed Workspace window error to use WorkspaceContainer

---

frontend/spa-build-config.json

Update spa-build-config.json - use ohri patient chart

---

frontend/spa-build-config.json

- Add the data visualizer module to ohri dev
- https://ohri.atlassian.net/browse/OHRI-2266

(Chore) Add uganda emr Data visualizer to ohri dev

---

packages/esm-ohri-pmtct-app/src/config-schema.ts

Rename Infant - postnatal Form to Infant - Postnatal Form

Rename Infant - postnatal Form to Infant - Postnatal Form

---

packages/esm-ohri-pmtct-app/src/pmtct/patient-chart/mch-summary/tabs/current-pregnancy.component.tsx

OHRI-2267 PTracker ID should show on the Family section patient list on MNCH summary

---

packages/esm-commons-lib/src/api.resource.ts
packages/esm-commons-lib/src/utils/summary-card-config-builder.ts
packages/esm-ohri-pmtct-app/src/pmtct/patient-chart/mch-summary/tabs/recent-pregnancy-config.json

- This adds encounterTypes to extract patient uuid and pass the pTracker ID to the `fetchMamba` report endpoint
- https://ohri.atlassian.net/browse/OHRI-2268

(fix) Add pTracker Id to the mamba report endpoint

---

frontend/spa-build-config.json

- Remove `Data Visualizer` from ohri
- No ticket

Remove data visualizer from ohri

---

packages/esm-commons-lib/src/components/reports/home.component.scss
packages/esm-commons-lib/src/components/reports/reportfilters.tsx
packages/esm-commons-lib/src/components/reports/reports-home.component.tsx
packages/esm-commons-lib/src/components/reports/reports-root.component.tsx
packages/esm-commons-lib/src/config-schema.ts

This PR displays a view of reports and their filters
https://ohri.atlassian.net/browse/OHRI-2306)

(Feat)- OHRI-2306-Basic Report View

---

packages/esm-ohri-pmtct-app/src/config-schema.ts

Change config default to false for widgets on PMTCT

---

package.json
packages/esm-form-render-app/package.json
yarn.lock

(chore) Bump FE

---

packages/esm-ohri-pmtct-app/src/pmtct/patient-chart/maternal-health/maternal-health-config.json

https://ohri.atlassian.net/browse/OHRI-2312
https://ohri.atlassian.net/browse/OHRI-2313
https://ohri.atlassian.net/browse/OHRI-2314

Minor changes to the PMTCT Encounter Tables

---

packages/esm-cervical-cancer-app/tsconfig.json
packages/esm-covid-app/tsconfig.json
packages/esm-hiv-care-treatment-app/tsconfig.json
packages/esm-hiv-prevention-app/tsconfig.json
packages/esm-ohri-pmtct-app/tsconfig.json
packages/esm-opd-app/tsconfig.json
packages/esm-tb-app/tsconfig.json
tsconfig.json

Upgrade TypeScript to support ES2022 features

(chore) Upgrade TypeScript to support ES2022 features

---

yarn.lock

(chore) Bump the react Form Engine version

(chore) Bump the react Form Engine version

---

package.json
packages/esm-cervical-cancer-app/package.json
packages/esm-commons-lib/package.json
packages/esm-covid-app/package.json
packages/esm-form-render-app/package.json
packages/esm-hiv-app/package.json
packages/esm-ohri-core-app/package.json
packages/esm-ohri-pmtct-app/package.json
packages/esm-opd-app/package.json
packages/esm-tb-app/package.json

- Update the package versions for release

Update package versions
